export const DOMAIN_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  TEST_ZONE_REPOSITORY: 'TEST_ZONE_REPOSITORY',
  BRAND_REPOSITORY: 'BRAND_REPOSITORY',
  ITEM_REPOSITORY: 'ITEM_REPOSITORY',
  PACKAGE_REPOSITORY: 'PACKAGE_REPOSITORY',
  ROUTE_REPOSITORY: 'ROUTE_REPOSITORY',
  STORAGE_UNIT_REPOSITORY: 'STORAGE_UNIT_REPOSITORY',
  USER_ROLE_REPOSITORY: 'USER_ROLE_REPOSITORY',
  REFRESH_TOKEN_REPOSITORY: 'REFRESH_TOKEN_REPOSITORY',
};
