export const SERVICE_TOKENS = {
  SANITIZATION_SERVICE: Symbol('SANITIZATION_SERVICE'),
  CRYPTO_SERVICE: Symbol('CRYPTO_SERVICE'),
  LOCAL_STORAGE_SERVICE: Symbol('LOCAL_STORAGE_SERVICE'),
} as const; 