export const SERVICE_TOKENS = {
  SANITIZATION_SERVICE: Symbol('SANITIZATION_SERVICE'),
  CRYPTO_SERVICE: Symbol('CRYPTO_SERVICE'),
  LOCAL_STORAGE_SERVICE: Symbol('LOCAL_STORAGE_SERVICE'),
  EMAIL_SERVICE: Symbol('EMAIL_SERVICE'),
  GOOGLE_VISION_SERVICE: Symbol('GOOGLE_VISION_SERVICE'),
} as const; 